# Generated by Django 6.0.5 on 2026-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cum', models.CharField(max_length=30, unique=True)),
                ('nombre_generico', models.CharField(max_length=255)),
                ('titular_registro', models.CharField(max_length=255)),
                ('concentracion', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('nombre_generico', 'cum'),
            },
        ),
    ]
