# Generated by Django 6.0.5 on 2026-05-31 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametricas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('OTRO', 'Otro')], max_length=10)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('registro_medico', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='FormulaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo_formula', models.CharField(blank=True, max_length=20, unique=True)),
                ('institucion', models.CharField(max_length=255)),
                ('fecha_formula', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='radicacion.afiliado')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='radicacion.medico')),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
        migrations.CreateModel(
            name='FormulaBaseTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('medicamento_nombre', models.CharField(blank=True, max_length=400)),
                ('cantidad_formulada', models.PositiveIntegerField()),
                ('dosis', models.CharField(blank=True, max_length=120)),
                ('indicaciones', models.TextField(blank=True)),
                ('contrato_asignado', models.CharField(blank=True, choices=[('CAPITA', 'Capita'), ('EVENTO', 'Evento')], max_length=20)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='radicacion.formulabase')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tecnologias', to='parametricas.medicamento')),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
        migrations.CreateModel(
            name='SoporteFormulaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('archivo', models.FileField(upload_to='soportes/')),
                ('tipo_soporte', models.CharField(choices=[('PRESCRIPCION', 'Prescripción'), ('AUTORIZACION', 'Autorización'), ('ANEXO', 'Anexo'), ('OTRO', 'Otro')], max_length=50)),
                ('medicamento_nombre', models.CharField(blank=True, max_length=400)),
                ('indicaciones', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('formula_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='radicacion.formulabase')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soportes', to='parametricas.medicamento')),
                ('usuario_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soportes_formula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
    ]
