# Generated by Django 6.0.5 on 2026-06-02 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametricas', '0001_initial'),
        ('radicacion', '0002_alter_formulabase_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporteformulabase',
            name='medicamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soportes', to='parametricas.medicamento'),
        ),
    ]
