# Generated by Django 6.0.5 on 2026-06-02 21:39

import radicacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0003_soporte_medicamento_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporteformulabase',
            name='archivo',
            field=models.FileField(upload_to=radicacion.models._soporte_upload_path),
        ),
    ]
