# Generated by Django 6.0.5 on 2026-06-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicacion', '0004_soporte_upload_path_callable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRegistroContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('medicamento_nombre', models.CharField(blank=True, max_length=400)),
                ('contrato_asignado', models.CharField(blank=True, choices=[('CAPITA', 'Capita'), ('EVENTO', 'Evento')], max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('TOTAL', 'Total'), ('PARCIAL', 'Parcial')], default='TOTAL', max_length=20)),
                ('dosis', models.CharField(blank=True, max_length=120)),
                ('periodo', models.CharField(blank=True, max_length=120)),
                ('cantidad_solicitada', models.PositiveIntegerField(default=0)),
                ('cantidad_formulada', models.PositiveIntegerField()),
                ('cantidad_entregada', models.PositiveIntegerField(default=0)),
                ('numero_entrega_actual', models.PositiveIntegerField(default=1)),
                ('numero_entregas_programadas', models.PositiveIntegerField(default=1)),
                ('observacion', models.TextField(blank=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_contrato', to='radicacion.formulabase')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_contrato', to='parametricas.medicamento')),
                ('tecnologia_origen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_contrato', to='radicacion.formulabasetecnologia')),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
    ]